# Generated by Django 5.2.4 on 2026-08-08 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(verbose_name='変換前')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversion_requests',
            },
        ),
        migrations.CreateModel(
            name='ConversionScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversion_scenes',
            },
        ),
        migrations.CreateModel(
            name='ConversionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_guest_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversion_targets',
            },
        ),
        migrations.CreateModel(
            name='ConversionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_text', models.TextField(verbose_name='変換後の文章')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversion_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='conversions.conversionrequest', verbose_name='変換リクエスト')),
            ],
            options={
                'db_table': 'conversion_results',
            },
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conversions.conversionscene', verbose_name='場面タイプ'),
        ),
        migrations.AddField(
            model_name='conversionrequest',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conversions.conversiontarget', verbose_name='変換タイプ'),
        ),
    ]
