# Generated by Django 5.2.4 on 2026-08-12 02:53

from django.db import migrations

def create_initial_master_data(apps, schema_editor): # 登録用マスタデータ
    ConversionTarget = apps.get_model( # マイグレーション時点のConversionTargetモデルを持ってくる
        "conversions", # アプリ名
        "ConversionTarget", # 取得するモデル
    )

    targets = [ # targetの登録データは以下
        {
            "name": "上司向け", # 表示名
            "code": "boss", # こいつの識別名
            "is_guest_available": True, # ゲストで使う
        },

        {
            "name": "社外向け", # 表示名
            "code": "external", # こいつの識別名
            "is_guest_available": False, # ゲストで使わない
        },

        {
            "name": "同僚向け", # 表示名
            "code": "coworker", # こいつの識別名
            "is_guest_available": False, # ゲストで使わない
        },

        {
            "name": "部下向け", # 表示名
            "code": "subordinate", # こいつの識別名
            "is_guest_available": False, # ゲストで使わない
        },
    ]

    for target in targets: # targetsの中身をtargetの名前で取り出す
        ConversionTarget.objects.update_or_create(
            code=target["code"], # targetからcodeで登録されているものを探す
            defaults={ # 見つからなければ下記内容を新規登録、見つかったら更新
                "name": target["name"],
                "is_guest_available": target["is_guest_available"],
            },
        )

    ConversionScene = apps.get_model( # マイグレーション時点のConversionSceneモデルを持ってくる
        "conversions", # アプリ名
        "ConversionScene", # 取得するモデル
    )


    scenes = [ # sceneの登録データは以下
        {
            "name": "依頼", # 表示名
            "code": "request", # こいつの識別名
        },

        {
            "name": "謝罪", # 表示名
            "code": "apology", # こいつの識別名
        },

        {
            "name": "報告", # 表示名
            "code": "report", # こいつの識別名
        },

        {
            "name": "お礼", # 表示名
            "code": "thanks", # こいつの識別名
        },

        {
            "name": "催促", # 表示名
            "code": "reminder", # こいつの識別名
        },

        {
            "name": "断り", # 表示名
            "code": "refusal", # こいつの識別名
        },
    ]

    for scene in scenes: # scenesの中身をsceneの名前で取り出す
        ConversionScene.objects.update_or_create(
            code=scene["code"], # sceneからcodeで登録されているものを探す
            defaults={ # 見つからなければ下記内容を新規登録、見つかったら更新
                "name": scene["name"],
            },
        )

# 下記自動生成文
class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_master_data, # このマイグレーションを適用するときに、create_initial_master_data()を実行する
            reverse_code=migrations.RunPython.noop, # 戻すときは何もしない
        ),
    ]
# ここまで