# Generated by Django 5.2.4 on 2026-08-27 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0003_conversionrequest_user_alter_conversionscene_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_count', models.IntegerField(default=0, verbose_name='変換回数')),
                ('count_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'guest_sessions',
            },
        ),
    ]
