# Generated by Django 5.2.4 on 2026-09-04 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0004_guestsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='プリセット名')),
                ('input_text', models.TextField(verbose_name='入力文章')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presets', to='conversions.conversionscene', verbose_name='場面タイプ')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presets', to='conversions.conversiontarget', verbose_name='変換タイプ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_presets', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'conversion_presets',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_conversion_preset_name_per_user')],
            },
        ),
    ]
